// AI-generated illustrative photos. Merchant uploads in Firestore take priority.
const paths = new Map([
  ["小白菜", "images/products/xiaobaicai.webp"],
  ["紅蔥頭", "images/products/shallots.webp"],
  ["地瓜葉", "images/products/sweet-potato-leaves.webp"],
  ["冬粉", "images/products/glass-noodles.webp"],
  ["老薑", "images/products/ginger.webp"],
  ["金針菇", "images/products/enoki.webp"],
  ["蒜頭", "images/products/garlic.webp"],
  ["水果彩椒", "images/products/mini-peppers.webp"],
  ["小刈菜", "images/products/mustard.webp"],
  ["嫩薑", "images/products/young-ginger.webp"],
  ["米粉", "images/products/rice-noodles.webp"],
  ["油菜", "images/products/yu-choy.webp"],
  ["青江菜", "images/products/bok-choy.webp"],
  ["牛蒡", "images/products/burdock.webp"],
  ["秋葵", "images/products/01.webp"],
  ["糯米椒", "images/products/02.webp"],
  ["杏鮑菇", "images/products/03.webp"],
  ["蘆筍", "images/products/04.webp"],
  ["空心菜", "images/products/05.webp"],
  ["地瓜", "images/products/06.webp"],
  ["黃玉米", "images/products/07.webp"],
  ["大陸妹", "images/products/08.webp"],
  ["馬鈴薯", "images/products/09.webp"],
  ["紫米玉米", "images/products/10.webp"],
  ["白蘿蔔", "images/products/11.webp"],
  ["彩椒", "images/products/12.webp"],
  ["青蔥", "images/products/13.webp"],
  ["長豆", "images/products/14.webp"],
  ["四季豆", "images/products/15.webp"],
  ["絲瓜", "images/products/16.webp"],
  ["貝貝南瓜", "images/products/17.webp"],
  ["芹菜", "images/products/18.webp"],
  ["現切竹筍", "images/products/19.webp"],
  ["香菜", "images/products/20.webp"],
  ["香菇", "images/products/21.webp"],
  ["茄子", "images/products/22.webp"],
  ["九層塔", "images/products/23.webp"],
  ["雙色菇", "images/products/24.webp"],
  ["苦瓜", "images/products/25.webp"],
  ["韭菜", "images/products/26.webp"],
  ["皇宮菜", "images/products/27.webp"],
  ["小黃瓜", "images/products/28.webp"],
  ["金瓜", "images/products/29.webp"],
  ["櫛瓜", "images/products/30.webp"],
  ["青花椰菜", "images/products/31.webp"],
  ["芋頭", "images/products/32.webp"],
  ["番茄", "images/products/33.webp"],
  ["皎白筍", "images/products/34.webp"],
  ["高麗菜", "images/products/35.webp"],
  ["竹筍", "images/products/36.webp"],
  ["西洋芹", "images/products/37.webp"],
  ["紅蘿蔔", "images/products/38.webp"],
  ["豆芽菜", "images/products/39.webp"],
  ["紅莧菜", "images/products/40.webp"],
  ["冬瓜", "images/products/41.webp"],
  ["龍鬚菜", "images/products/42.webp"],
  ["玉米筍", "images/products/43.webp"],
  ["洋蔥", "images/products/44.webp"],
  ["韓國白菜", "images/products/45.webp"]
]);
export function generatedPhotoFor(name) {
  const path = paths.get(String(name || "").trim());
  return path ? new URL(path, import.meta.url).href : "";
}
