import assert from 'node:assert/strict';
import {generateKeyPairSync,createHmac} from 'node:crypto';
import {authenticatedMember,memberOrdersApi} from './member-orders.mjs';
import {orderApi} from './order-service.mjs';
const sub='U'+'a'.repeat(32),other='U'+'b'.repeat(32),secret='test-strong-line-channel-secret';
const sign=(claims,key=secret+':member-v2')=>{const unsigned=Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url')+'.'+Buffer.from(JSON.stringify(claims)).toString('base64url');return unsigned+'.'+createHmac('sha256',key).update(unsigned).digest('base64url')};
const token=sign({sub,name:'會員',exp:Date.now()/1000+3600});
const env={LINE_CHANNEL_SECRET:secret};
const request=(t=token)=>new Request('https://example.test/member/orders?memberId='+other,{headers:t?{Authorization:'Bearer '+t}:{}});
assert.equal((await authenticatedMember(request(),env)).sub,sub);
for(const t of ['',token+'x',sign({sub,exp:1}),sign({sub,exp:Date.now()/1000+3600},'old-secret'),sign({sub:'invalid',exp:Date.now()/1000+3600})]) assert.equal((await memberOrdersApi(request(t),env)).status,401);
const {privateKey}=generateKeyPairSync('rsa',{modulusLength:2048});
env.FIRESTORE_READER_JSON=JSON.stringify({project_id:'apple-6b54f',client_email:'test@example.test',private_key:privateKey.export({type:'pkcs8',format:'pem'})});
let calls=0,fail=false;
globalThis.fetch=async(url,options)=>{
 calls++;
 if(url.includes('oauth2'))return Response.json({access_token:'test-access',expires_in:3600});
 assert.equal(JSON.parse(options.body).structuredQuery.where.fieldFilter.value.stringValue,sub);
 if(fail)return Response.json({error:'failed'},{status:403});
 const doc=(id,owner,date)=>({document:{name:'orders/'+id,fields:{memberId:{stringValue:owner},customerPhone:{stringValue:'private'},createdAt:{timestampValue:date},status:{stringValue:'preparing'},total:{doubleValue:50},items:{arrayValue:{values:[]}}}}});
 return Response.json([doc('older',sub,'2026-10-01T01:00:00Z'),doc('foreign',other,'2026-10-05T01:00:00Z'),doc('latest',sub,'2026-10-04T01:00:00Z')]);
};
const result=await (await memberOrdersApi(request(),env)).json();
assert.deepEqual(result.orders.map(o=>o.id),['latest','older']);assert.equal(result.orders[0].status,'preparing');assert.ok(!JSON.stringify(result).includes('private'));assert.ok(!JSON.stringify(result).includes(other));
fail=true;assert.equal((await memberOrdersApi(request(),env)).status,503);
assert.equal((await memberOrdersApi(new Request('https://example.test',{method:'OPTIONS'}),env)).status,204);
const order={customerName:'test',customerPhone:'000',note:'',items:[{name:'菜',unit:'包',price:20,qty:1}],total:20,memberLoggedIn:true,memberId:other};
const before=calls;
const response=await orderApi(new Request('https://example.test/orders',{method:'POST',headers:{Origin:'https://twm0987373440-sketch.github.io',Authorization:'Bearer '+token},body:JSON.stringify({requestId:crypto.randomUUID(),order})}),{...env,ORDER_DB:{},LINE_CHANNEL_ACCESS_TOKEN:'test',LINE_OWNER_USER_ID:sub},{},authenticatedMember);
assert.equal(response.status,401);assert.equal(calls,before);
console.log('PASS: authentication, expiry, tampering, old-token rejection, verified owner filter, foreign-order exclusion, privacy projection, chronological history, status, upstream failure, preflight, checkout identity spoof rejection.');
